authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that returns hello."
name = "spin-hello-world"
spin_version = "1"
trigger = {type = "http", base = "/"}
version = "1.0.0"

[config]
discord_bot_token = {required = true}
discord_pub_key = {required = true}

[[component]]
allowed_http_hosts = ["https://discord.com/api/v10/applications"]
description = "A simple component that returns hello."
environment = {DISCORD_PUB_KEY = "{{discord_pub_key}}", DISCORD_BOT_TOKEN = "{{discord_bot_token}}"}
id = "hello"
source = "target/wasm32-wasi/release/spinhelloworld.wasm"
[component.trigger]
route = "/api/interactions"
[component.build]
command = "cargo build --target wasm32-wasi --release"
