authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that returns hello."
name = "spin-hello-world"
spin_version = "1"
trigger = {type = "http", base = "/"}
version = "1.0.0"

[[component]]
description = "A simple component that returns hello."
environment = {DISCORD_PUB_KEY = "9c2cddc3eae3513c137e87da915a763252469ea955a3d6e9d43133e081bdfb35"}
id = "hello"
source = "target/wasm32-wasi/release/spinhelloworld.wasm"
[component.trigger]
route = "/api/interactions"
[component.build]
command = "cargo build --target wasm32-wasi --release"
